[package]
name = "range"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
either = "1.8.0"
glam = "0.22.0"
int-enum = "0.5.0"
ndarray = "0.15.6"
pom = "3.2.0"
