[package]
name = "valve"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi_term = "0.12.1"
either = "1.8.0"
itertools = "0.10.5"
petgraph = "0.6.2"
pom = "3.2.0"
