[package]
name = "search"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi_term = "0.12.1"
char_reader = "0.1.1"
glam = "0.22.0"
ndarray = "0.15.6"
ordered-float = "3.4.0"
pathfinding = "4.0.0"
